[package]
name = "rust-duplicate-img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.1"
walkdir = "2.3.1"
rfd = "0.13.0"